---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/merchants":
    post:
      summary: create merchant
      tags:
      - Merchants
      parameters: []
      responses:
        '201':
          description: merchant created
        '422':
          description: unprocessable entity
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                reference:
                  type: string
                  example: MERCH123
                email:
                  type: string
                  example: merchant@example.com
                live_on:
                  type: string
                  format: date
                  example: '2024-03-20'
                disbursement_frequency:
                  type: string
                  enum:
                  - daily
                  - weekly
                  example: daily
                minimum_monthly_fee:
                  type: number
                  format: float
                  example: 29.99
              required:
              - reference
              - email
              - live_on
              - disbursement_frequency
  "/api/v1/orders":
    post:
      summary: create order
      tags:
      - Orders
      parameters: []
      responses:
        '201':
          description: order created
        '422':
          description: unprocessable entity
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                merchant_reference:
                  type: string
                  example: ORDER123
                amount:
                  type: number
                  format: float
                  example: 100.5
                created_at:
                  type: string
                  format: date-time
                  example: '2024-03-20T10:00:00Z'
              required:
              - merchant_reference
              - amount
              - created_at
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
